apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJvYmVtLWRvY2tlci1kZXYtbG9jYWwuamZyb2ctcHJvZC5kZWJzcmVwbGF0Zm9ybS5jbG91ZCI6eyJ1c2VybmFtZSI6ImRlYmFkbWludXNlciIsInBhc3N3b3JkIjoiTjgzVjVGVHRIelc0c1BoOSIsImF1dGgiOiJaR1ZpWVdSdGFXNTFjMlZ5T2s0NE0xWTFSbFIwU0hwWE5ITlFhRGs9In19fQ==
kind: Secret
metadata:
  name: jfrog-auth-secret
type: kubernetes.io/dockerconfigjson