apiVersion: v1
kind: Secret
metadata:
  name: vault-cred
type: Opaque
stringData:
  VAULT_ADDR: https://vault-nonprod.debsreplatform.cloud:8200/
  VAULT_TOKEN: hvs.CAESIC_EDbh1jTJ2Tlo1Z2nEl4DnLGmdoXoZNToLMu8HskyDGiIKHGh2cy5kQ2VRQ3cyb09UQlpTRlNjamR5OHdxeWkQu_xm


